name: news_service
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^1.0.1
  dart_jsonwebtoken: ^2.6.4
  dbcrypt: ^2.0.0
  email_validator: ^2.1.17
  logging: ^1.1.1
  postgres: ^2.5.2
  uuid: ^3.0.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
